/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as MathImport } from './routes/math'
import { Route as HijosImport } from './routes/hijos'
import { Route as AiImport } from './routes/ai'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PapasIndexImport } from './routes/papas/index'
import { Route as LeccionesIndexImport } from './routes/lecciones.index'
import { Route as HijosIndexImport } from './routes/hijos/index'
import { Route as PapasLessonIdImport } from './routes/papas/$lessonId'
import { Route as HijosLessonIdImport } from './routes/hijos/$lessonId'
import { Route as LeccionesLessonIdIndexImport } from './routes/lecciones.$lessonId.index'
import { Route as HijosLessonIdIndexImport } from './routes/hijos/$lessonId.index'
import { Route as HijosLessonIdLessonStepIdImport } from './routes/hijos/$lessonId.$lessonStepId'
import { Route as LeccionesLessonIdPasoLessonStepIdImport } from './routes/lecciones.$lessonId.paso.$lessonStepId'

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const MathRoute = MathImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => rootRoute,
} as any)

const HijosRoute = HijosImport.update({
  id: '/hijos',
  path: '/hijos',
  getParentRoute: () => rootRoute,
} as any)

const AiRoute = AiImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PapasIndexRoute = PapasIndexImport.update({
  id: '/papas/',
  path: '/papas/',
  getParentRoute: () => rootRoute,
} as any)

const LeccionesIndexRoute = LeccionesIndexImport.update({
  id: '/lecciones/',
  path: '/lecciones/',
  getParentRoute: () => rootRoute,
} as any)

const HijosIndexRoute = HijosIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HijosRoute,
} as any)

const PapasLessonIdRoute = PapasLessonIdImport.update({
  id: '/papas/$lessonId',
  path: '/papas/$lessonId',
  getParentRoute: () => rootRoute,
} as any)

const HijosLessonIdRoute = HijosLessonIdImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => HijosRoute,
} as any)

const LeccionesLessonIdIndexRoute = LeccionesLessonIdIndexImport.update({
  id: '/lecciones/$lessonId/',
  path: '/lecciones/$lessonId/',
  getParentRoute: () => rootRoute,
} as any)

const HijosLessonIdIndexRoute = HijosLessonIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HijosLessonIdRoute,
} as any)

const HijosLessonIdLessonStepIdRoute = HijosLessonIdLessonStepIdImport.update({
  id: '/$lessonStepId',
  path: '/$lessonStepId',
  getParentRoute: () => HijosLessonIdRoute,
} as any)

const LeccionesLessonIdPasoLessonStepIdRoute =
  LeccionesLessonIdPasoLessonStepIdImport.update({
    id: '/lecciones/$lessonId/paso/$lessonStepId',
    path: '/lecciones/$lessonId/paso/$lessonStepId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiImport
      parentRoute: typeof rootRoute
    }
    '/hijos': {
      id: '/hijos'
      path: '/hijos'
      fullPath: '/hijos'
      preLoaderRoute: typeof HijosImport
      parentRoute: typeof rootRoute
    }
    '/math': {
      id: '/math'
      path: '/math'
      fullPath: '/math'
      preLoaderRoute: typeof MathImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/hijos/$lessonId': {
      id: '/hijos/$lessonId'
      path: '/$lessonId'
      fullPath: '/hijos/$lessonId'
      preLoaderRoute: typeof HijosLessonIdImport
      parentRoute: typeof HijosImport
    }
    '/papas/$lessonId': {
      id: '/papas/$lessonId'
      path: '/papas/$lessonId'
      fullPath: '/papas/$lessonId'
      preLoaderRoute: typeof PapasLessonIdImport
      parentRoute: typeof rootRoute
    }
    '/hijos/': {
      id: '/hijos/'
      path: '/'
      fullPath: '/hijos/'
      preLoaderRoute: typeof HijosIndexImport
      parentRoute: typeof HijosImport
    }
    '/lecciones/': {
      id: '/lecciones/'
      path: '/lecciones'
      fullPath: '/lecciones'
      preLoaderRoute: typeof LeccionesIndexImport
      parentRoute: typeof rootRoute
    }
    '/papas/': {
      id: '/papas/'
      path: '/papas'
      fullPath: '/papas'
      preLoaderRoute: typeof PapasIndexImport
      parentRoute: typeof rootRoute
    }
    '/hijos/$lessonId/$lessonStepId': {
      id: '/hijos/$lessonId/$lessonStepId'
      path: '/$lessonStepId'
      fullPath: '/hijos/$lessonId/$lessonStepId'
      preLoaderRoute: typeof HijosLessonIdLessonStepIdImport
      parentRoute: typeof HijosLessonIdImport
    }
    '/hijos/$lessonId/': {
      id: '/hijos/$lessonId/'
      path: '/'
      fullPath: '/hijos/$lessonId/'
      preLoaderRoute: typeof HijosLessonIdIndexImport
      parentRoute: typeof HijosLessonIdImport
    }
    '/lecciones/$lessonId/': {
      id: '/lecciones/$lessonId/'
      path: '/lecciones/$lessonId'
      fullPath: '/lecciones/$lessonId'
      preLoaderRoute: typeof LeccionesLessonIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/lecciones/$lessonId/paso/$lessonStepId': {
      id: '/lecciones/$lessonId/paso/$lessonStepId'
      path: '/lecciones/$lessonId/paso/$lessonStepId'
      fullPath: '/lecciones/$lessonId/paso/$lessonStepId'
      preLoaderRoute: typeof LeccionesLessonIdPasoLessonStepIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface HijosLessonIdRouteChildren {
  HijosLessonIdLessonStepIdRoute: typeof HijosLessonIdLessonStepIdRoute
  HijosLessonIdIndexRoute: typeof HijosLessonIdIndexRoute
}

const HijosLessonIdRouteChildren: HijosLessonIdRouteChildren = {
  HijosLessonIdLessonStepIdRoute: HijosLessonIdLessonStepIdRoute,
  HijosLessonIdIndexRoute: HijosLessonIdIndexRoute,
}

const HijosLessonIdRouteWithChildren = HijosLessonIdRoute._addFileChildren(
  HijosLessonIdRouteChildren,
)

interface HijosRouteChildren {
  HijosLessonIdRoute: typeof HijosLessonIdRouteWithChildren
  HijosIndexRoute: typeof HijosIndexRoute
}

const HijosRouteChildren: HijosRouteChildren = {
  HijosLessonIdRoute: HijosLessonIdRouteWithChildren,
  HijosIndexRoute: HijosIndexRoute,
}

const HijosRouteWithChildren = HijosRoute._addFileChildren(HijosRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/hijos': typeof HijosRouteWithChildren
  '/math': typeof MathRoute
  '/onboarding': typeof OnboardingRoute
  '/hijos/$lessonId': typeof HijosLessonIdRouteWithChildren
  '/papas/$lessonId': typeof PapasLessonIdRoute
  '/hijos/': typeof HijosIndexRoute
  '/lecciones': typeof LeccionesIndexRoute
  '/papas': typeof PapasIndexRoute
  '/hijos/$lessonId/$lessonStepId': typeof HijosLessonIdLessonStepIdRoute
  '/hijos/$lessonId/': typeof HijosLessonIdIndexRoute
  '/lecciones/$lessonId': typeof LeccionesLessonIdIndexRoute
  '/lecciones/$lessonId/paso/$lessonStepId': typeof LeccionesLessonIdPasoLessonStepIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/math': typeof MathRoute
  '/onboarding': typeof OnboardingRoute
  '/papas/$lessonId': typeof PapasLessonIdRoute
  '/hijos': typeof HijosIndexRoute
  '/lecciones': typeof LeccionesIndexRoute
  '/papas': typeof PapasIndexRoute
  '/hijos/$lessonId/$lessonStepId': typeof HijosLessonIdLessonStepIdRoute
  '/hijos/$lessonId': typeof HijosLessonIdIndexRoute
  '/lecciones/$lessonId': typeof LeccionesLessonIdIndexRoute
  '/lecciones/$lessonId/paso/$lessonStepId': typeof LeccionesLessonIdPasoLessonStepIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/hijos': typeof HijosRouteWithChildren
  '/math': typeof MathRoute
  '/onboarding': typeof OnboardingRoute
  '/hijos/$lessonId': typeof HijosLessonIdRouteWithChildren
  '/papas/$lessonId': typeof PapasLessonIdRoute
  '/hijos/': typeof HijosIndexRoute
  '/lecciones/': typeof LeccionesIndexRoute
  '/papas/': typeof PapasIndexRoute
  '/hijos/$lessonId/$lessonStepId': typeof HijosLessonIdLessonStepIdRoute
  '/hijos/$lessonId/': typeof HijosLessonIdIndexRoute
  '/lecciones/$lessonId/': typeof LeccionesLessonIdIndexRoute
  '/lecciones/$lessonId/paso/$lessonStepId': typeof LeccionesLessonIdPasoLessonStepIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai'
    | '/hijos'
    | '/math'
    | '/onboarding'
    | '/hijos/$lessonId'
    | '/papas/$lessonId'
    | '/hijos/'
    | '/lecciones'
    | '/papas'
    | '/hijos/$lessonId/$lessonStepId'
    | '/hijos/$lessonId/'
    | '/lecciones/$lessonId'
    | '/lecciones/$lessonId/paso/$lessonStepId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai'
    | '/math'
    | '/onboarding'
    | '/papas/$lessonId'
    | '/hijos'
    | '/lecciones'
    | '/papas'
    | '/hijos/$lessonId/$lessonStepId'
    | '/hijos/$lessonId'
    | '/lecciones/$lessonId'
    | '/lecciones/$lessonId/paso/$lessonStepId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai'
    | '/hijos'
    | '/math'
    | '/onboarding'
    | '/hijos/$lessonId'
    | '/papas/$lessonId'
    | '/hijos/'
    | '/lecciones/'
    | '/papas/'
    | '/hijos/$lessonId/$lessonStepId'
    | '/hijos/$lessonId/'
    | '/lecciones/$lessonId/'
    | '/lecciones/$lessonId/paso/$lessonStepId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiRoute: typeof AiRoute
  HijosRoute: typeof HijosRouteWithChildren
  MathRoute: typeof MathRoute
  OnboardingRoute: typeof OnboardingRoute
  PapasLessonIdRoute: typeof PapasLessonIdRoute
  LeccionesIndexRoute: typeof LeccionesIndexRoute
  PapasIndexRoute: typeof PapasIndexRoute
  LeccionesLessonIdIndexRoute: typeof LeccionesLessonIdIndexRoute
  LeccionesLessonIdPasoLessonStepIdRoute: typeof LeccionesLessonIdPasoLessonStepIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiRoute: AiRoute,
  HijosRoute: HijosRouteWithChildren,
  MathRoute: MathRoute,
  OnboardingRoute: OnboardingRoute,
  PapasLessonIdRoute: PapasLessonIdRoute,
  LeccionesIndexRoute: LeccionesIndexRoute,
  PapasIndexRoute: PapasIndexRoute,
  LeccionesLessonIdIndexRoute: LeccionesLessonIdIndexRoute,
  LeccionesLessonIdPasoLessonStepIdRoute:
    LeccionesLessonIdPasoLessonStepIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/ai",
        "/hijos",
        "/math",
        "/onboarding",
        "/papas/$lessonId",
        "/lecciones/",
        "/papas/",
        "/lecciones/$lessonId/",
        "/lecciones/$lessonId/paso/$lessonStepId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/ai": {
      "filePath": "ai.tsx"
    },
    "/hijos": {
      "filePath": "hijos.tsx",
      "children": [
        "/hijos/$lessonId",
        "/hijos/"
      ]
    },
    "/math": {
      "filePath": "math.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/hijos/$lessonId": {
      "filePath": "hijos/$lessonId.tsx",
      "parent": "/hijos",
      "children": [
        "/hijos/$lessonId/$lessonStepId",
        "/hijos/$lessonId/"
      ]
    },
    "/papas/$lessonId": {
      "filePath": "papas/$lessonId.tsx"
    },
    "/hijos/": {
      "filePath": "hijos/index.tsx",
      "parent": "/hijos"
    },
    "/lecciones/": {
      "filePath": "lecciones.index.tsx"
    },
    "/papas/": {
      "filePath": "papas/index.tsx"
    },
    "/hijos/$lessonId/$lessonStepId": {
      "filePath": "hijos/$lessonId.$lessonStepId.tsx",
      "parent": "/hijos/$lessonId"
    },
    "/hijos/$lessonId/": {
      "filePath": "hijos/$lessonId.index.tsx",
      "parent": "/hijos/$lessonId"
    },
    "/lecciones/$lessonId/": {
      "filePath": "lecciones.$lessonId.index.tsx"
    },
    "/lecciones/$lessonId/paso/$lessonStepId": {
      "filePath": "lecciones.$lessonId.paso.$lessonStepId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
