/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as MathImport } from './routes/math'
import { Route as HijosImport } from './routes/hijos'
import { Route as IndexImport } from './routes/index'
import { Route as PapasIndexImport } from './routes/papas/index'
import { Route as HijosIndexImport } from './routes/hijos/index'
import { Route as PapasLessonIdImport } from './routes/papas/$lessonId'
import { Route as HijosLessonIdImport } from './routes/hijos/$lessonId'
import { Route as PapasLessonIdIndexImport } from './routes/papas/$lessonId.index'
import { Route as HijosLessonIdIndexImport } from './routes/hijos/$lessonId.index'
import { Route as PapasLessonIdResultadosImport } from './routes/papas/$lessonId.resultados'
import { Route as HijosLessonIdEndImport } from './routes/hijos/$lessonId.end'
import { Route as HijosLessonIdLessonStepIdImport } from './routes/hijos/$lessonId.$lessonStepId'

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const MathRoute = MathImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => rootRoute,
} as any)

const HijosRoute = HijosImport.update({
  id: '/hijos',
  path: '/hijos',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PapasIndexRoute = PapasIndexImport.update({
  id: '/papas/',
  path: '/papas/',
  getParentRoute: () => rootRoute,
} as any)

const HijosIndexRoute = HijosIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HijosRoute,
} as any)

const PapasLessonIdRoute = PapasLessonIdImport.update({
  id: '/papas/$lessonId',
  path: '/papas/$lessonId',
  getParentRoute: () => rootRoute,
} as any)

const HijosLessonIdRoute = HijosLessonIdImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => HijosRoute,
} as any)

const PapasLessonIdIndexRoute = PapasLessonIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PapasLessonIdRoute,
} as any)

const HijosLessonIdIndexRoute = HijosLessonIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HijosLessonIdRoute,
} as any)

const PapasLessonIdResultadosRoute = PapasLessonIdResultadosImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => PapasLessonIdRoute,
} as any)

const HijosLessonIdEndRoute = HijosLessonIdEndImport.update({
  id: '/end',
  path: '/end',
  getParentRoute: () => HijosLessonIdRoute,
} as any)

const HijosLessonIdLessonStepIdRoute = HijosLessonIdLessonStepIdImport.update({
  id: '/$lessonStepId',
  path: '/$lessonStepId',
  getParentRoute: () => HijosLessonIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/hijos': {
      id: '/hijos'
      path: '/hijos'
      fullPath: '/hijos'
      preLoaderRoute: typeof HijosImport
      parentRoute: typeof rootRoute
    }
    '/math': {
      id: '/math'
      path: '/math'
      fullPath: '/math'
      preLoaderRoute: typeof MathImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/hijos/$lessonId': {
      id: '/hijos/$lessonId'
      path: '/$lessonId'
      fullPath: '/hijos/$lessonId'
      preLoaderRoute: typeof HijosLessonIdImport
      parentRoute: typeof HijosImport
    }
    '/papas/$lessonId': {
      id: '/papas/$lessonId'
      path: '/papas/$lessonId'
      fullPath: '/papas/$lessonId'
      preLoaderRoute: typeof PapasLessonIdImport
      parentRoute: typeof rootRoute
    }
    '/hijos/': {
      id: '/hijos/'
      path: '/'
      fullPath: '/hijos/'
      preLoaderRoute: typeof HijosIndexImport
      parentRoute: typeof HijosImport
    }
    '/papas/': {
      id: '/papas/'
      path: '/papas'
      fullPath: '/papas'
      preLoaderRoute: typeof PapasIndexImport
      parentRoute: typeof rootRoute
    }
    '/hijos/$lessonId/$lessonStepId': {
      id: '/hijos/$lessonId/$lessonStepId'
      path: '/$lessonStepId'
      fullPath: '/hijos/$lessonId/$lessonStepId'
      preLoaderRoute: typeof HijosLessonIdLessonStepIdImport
      parentRoute: typeof HijosLessonIdImport
    }
    '/hijos/$lessonId/end': {
      id: '/hijos/$lessonId/end'
      path: '/end'
      fullPath: '/hijos/$lessonId/end'
      preLoaderRoute: typeof HijosLessonIdEndImport
      parentRoute: typeof HijosLessonIdImport
    }
    '/papas/$lessonId/resultados': {
      id: '/papas/$lessonId/resultados'
      path: '/resultados'
      fullPath: '/papas/$lessonId/resultados'
      preLoaderRoute: typeof PapasLessonIdResultadosImport
      parentRoute: typeof PapasLessonIdImport
    }
    '/hijos/$lessonId/': {
      id: '/hijos/$lessonId/'
      path: '/'
      fullPath: '/hijos/$lessonId/'
      preLoaderRoute: typeof HijosLessonIdIndexImport
      parentRoute: typeof HijosLessonIdImport
    }
    '/papas/$lessonId/': {
      id: '/papas/$lessonId/'
      path: '/'
      fullPath: '/papas/$lessonId/'
      preLoaderRoute: typeof PapasLessonIdIndexImport
      parentRoute: typeof PapasLessonIdImport
    }
  }
}

// Create and export the route tree

interface HijosLessonIdRouteChildren {
  HijosLessonIdLessonStepIdRoute: typeof HijosLessonIdLessonStepIdRoute
  HijosLessonIdEndRoute: typeof HijosLessonIdEndRoute
  HijosLessonIdIndexRoute: typeof HijosLessonIdIndexRoute
}

const HijosLessonIdRouteChildren: HijosLessonIdRouteChildren = {
  HijosLessonIdLessonStepIdRoute: HijosLessonIdLessonStepIdRoute,
  HijosLessonIdEndRoute: HijosLessonIdEndRoute,
  HijosLessonIdIndexRoute: HijosLessonIdIndexRoute,
}

const HijosLessonIdRouteWithChildren = HijosLessonIdRoute._addFileChildren(
  HijosLessonIdRouteChildren,
)

interface HijosRouteChildren {
  HijosLessonIdRoute: typeof HijosLessonIdRouteWithChildren
  HijosIndexRoute: typeof HijosIndexRoute
}

const HijosRouteChildren: HijosRouteChildren = {
  HijosLessonIdRoute: HijosLessonIdRouteWithChildren,
  HijosIndexRoute: HijosIndexRoute,
}

const HijosRouteWithChildren = HijosRoute._addFileChildren(HijosRouteChildren)

interface PapasLessonIdRouteChildren {
  PapasLessonIdResultadosRoute: typeof PapasLessonIdResultadosRoute
  PapasLessonIdIndexRoute: typeof PapasLessonIdIndexRoute
}

const PapasLessonIdRouteChildren: PapasLessonIdRouteChildren = {
  PapasLessonIdResultadosRoute: PapasLessonIdResultadosRoute,
  PapasLessonIdIndexRoute: PapasLessonIdIndexRoute,
}

const PapasLessonIdRouteWithChildren = PapasLessonIdRoute._addFileChildren(
  PapasLessonIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hijos': typeof HijosRouteWithChildren
  '/math': typeof MathRoute
  '/onboarding': typeof OnboardingRoute
  '/hijos/$lessonId': typeof HijosLessonIdRouteWithChildren
  '/papas/$lessonId': typeof PapasLessonIdRouteWithChildren
  '/hijos/': typeof HijosIndexRoute
  '/papas': typeof PapasIndexRoute
  '/hijos/$lessonId/$lessonStepId': typeof HijosLessonIdLessonStepIdRoute
  '/hijos/$lessonId/end': typeof HijosLessonIdEndRoute
  '/papas/$lessonId/resultados': typeof PapasLessonIdResultadosRoute
  '/hijos/$lessonId/': typeof HijosLessonIdIndexRoute
  '/papas/$lessonId/': typeof PapasLessonIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/math': typeof MathRoute
  '/onboarding': typeof OnboardingRoute
  '/hijos': typeof HijosIndexRoute
  '/papas': typeof PapasIndexRoute
  '/hijos/$lessonId/$lessonStepId': typeof HijosLessonIdLessonStepIdRoute
  '/hijos/$lessonId/end': typeof HijosLessonIdEndRoute
  '/papas/$lessonId/resultados': typeof PapasLessonIdResultadosRoute
  '/hijos/$lessonId': typeof HijosLessonIdIndexRoute
  '/papas/$lessonId': typeof PapasLessonIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/hijos': typeof HijosRouteWithChildren
  '/math': typeof MathRoute
  '/onboarding': typeof OnboardingRoute
  '/hijos/$lessonId': typeof HijosLessonIdRouteWithChildren
  '/papas/$lessonId': typeof PapasLessonIdRouteWithChildren
  '/hijos/': typeof HijosIndexRoute
  '/papas/': typeof PapasIndexRoute
  '/hijos/$lessonId/$lessonStepId': typeof HijosLessonIdLessonStepIdRoute
  '/hijos/$lessonId/end': typeof HijosLessonIdEndRoute
  '/papas/$lessonId/resultados': typeof PapasLessonIdResultadosRoute
  '/hijos/$lessonId/': typeof HijosLessonIdIndexRoute
  '/papas/$lessonId/': typeof PapasLessonIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hijos'
    | '/math'
    | '/onboarding'
    | '/hijos/$lessonId'
    | '/papas/$lessonId'
    | '/hijos/'
    | '/papas'
    | '/hijos/$lessonId/$lessonStepId'
    | '/hijos/$lessonId/end'
    | '/papas/$lessonId/resultados'
    | '/hijos/$lessonId/'
    | '/papas/$lessonId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/math'
    | '/onboarding'
    | '/hijos'
    | '/papas'
    | '/hijos/$lessonId/$lessonStepId'
    | '/hijos/$lessonId/end'
    | '/papas/$lessonId/resultados'
    | '/hijos/$lessonId'
    | '/papas/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/hijos'
    | '/math'
    | '/onboarding'
    | '/hijos/$lessonId'
    | '/papas/$lessonId'
    | '/hijos/'
    | '/papas/'
    | '/hijos/$lessonId/$lessonStepId'
    | '/hijos/$lessonId/end'
    | '/papas/$lessonId/resultados'
    | '/hijos/$lessonId/'
    | '/papas/$lessonId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HijosRoute: typeof HijosRouteWithChildren
  MathRoute: typeof MathRoute
  OnboardingRoute: typeof OnboardingRoute
  PapasLessonIdRoute: typeof PapasLessonIdRouteWithChildren
  PapasIndexRoute: typeof PapasIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HijosRoute: HijosRouteWithChildren,
  MathRoute: MathRoute,
  OnboardingRoute: OnboardingRoute,
  PapasLessonIdRoute: PapasLessonIdRouteWithChildren,
  PapasIndexRoute: PapasIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/hijos",
        "/math",
        "/onboarding",
        "/papas/$lessonId",
        "/papas/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/hijos": {
      "filePath": "hijos.tsx",
      "children": [
        "/hijos/$lessonId",
        "/hijos/"
      ]
    },
    "/math": {
      "filePath": "math.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/hijos/$lessonId": {
      "filePath": "hijos/$lessonId.tsx",
      "parent": "/hijos",
      "children": [
        "/hijos/$lessonId/$lessonStepId",
        "/hijos/$lessonId/end",
        "/hijos/$lessonId/"
      ]
    },
    "/papas/$lessonId": {
      "filePath": "papas/$lessonId.tsx",
      "children": [
        "/papas/$lessonId/resultados",
        "/papas/$lessonId/"
      ]
    },
    "/hijos/": {
      "filePath": "hijos/index.tsx",
      "parent": "/hijos"
    },
    "/papas/": {
      "filePath": "papas/index.tsx"
    },
    "/hijos/$lessonId/$lessonStepId": {
      "filePath": "hijos/$lessonId.$lessonStepId.tsx",
      "parent": "/hijos/$lessonId"
    },
    "/hijos/$lessonId/end": {
      "filePath": "hijos/$lessonId.end.tsx",
      "parent": "/hijos/$lessonId"
    },
    "/papas/$lessonId/resultados": {
      "filePath": "papas/$lessonId.resultados.tsx",
      "parent": "/papas/$lessonId"
    },
    "/hijos/$lessonId/": {
      "filePath": "hijos/$lessonId.index.tsx",
      "parent": "/hijos/$lessonId"
    },
    "/papas/$lessonId/": {
      "filePath": "papas/$lessonId.index.tsx",
      "parent": "/papas/$lessonId"
    }
  }
}
ROUTE_MANIFEST_END */
